<?php

namespace Itransition\DataImporterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductItemRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT COUNT(*) FROM ItransitionDataImporterBundle:Product')
                    ->getResult();
    }
}
